checkpoint::checkpoint("2020-05-01", R.version = "3.6.3")
if (!require("DBI")) install.packages("DBI")
if (!require("RPostgreSQL")) install.packages("RPostgreSQL")
if (!require("dplyr")) install.packages("dplyr")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("shiny")) install.packages("shiny")
if (!require("dplyr")) install.packages("dplyr")
if (!require("dplyr")) install.packages("dplyr")
if (!require("dplyr")) install.packages("dplyr")
